[env]
_.path = [ "./node_modules/.bin" ]

[tools]
bun = "latest"
aube = "latest"

[tasks.prepare]
run = "mise generate git-pre-commit --write"

[tasks.pre-commit]
run = "nano-staged"

[tasks.build]
run = "echo 'Build completed!'"

[tasks.lint]
run = [
  "aubr oxlint",
  "aubr eslint"
]

[tasks."lint:fix"]
run = [ # Runnings are performed sequentially
  "aubr oxlint --fix",
  "aubr eslint --fix"
]

[tasks.typecheck]
run = "echo 'Type check successful!'"

[tasks.unused]
run = "echo 'Unused check successful!'"

[tasks.check]
run = { tasks = [ # Tasks are performed parallely
  "lint",
  "typecheck",
  "unused"
] }

[tasks.test]
run = "echo 'Tests passed!'"

[tasks.prerelease]
run = { tasks = [
  "check",
  "test"
] }

[tasks.release]
depends = "prerelease"
run = "aubr release"
raw = true
depends_post = "postrelease"

[tasks.postrelease]
run = "bun run ./release.sh"
