[env]
_.path = [ "./node_modules/.bin" ]

[tools]
bun = "latest"
aube = "latest"
pkl = "latest"
hk = "latest"

[hooks]
enter = "hk install"

[deps.auto-aube]
sources = [
  "package.json",
  "bun.lock"
]
outputs = [ "node_modules/" ]
run = "aube install"
auto = true

[tasks.pre-commit]
run = "hk run pre-commit"

[tasks.build]
run = "echo 'Build completed!'"

[tasks.check]
run = "hk check --all"

[tasks.fix]
run = "hk fix --all"

[tasks.test]
run = "echo 'Tests passed!'"

[tasks.prerelease]
run = { tasks = [
  "check",
  "test"
] }

[tasks.release]
depends = "prerelease"
run = "bumpp"
raw = true
depends_post = "postrelease"

[tasks.postrelease]
run = "bun run ./release.sh"
