[env]
_.path = [ "./node_modules/.bin" ]

[tools]
# Environments
bun = "1.3.14"
aube = "1.22.0"
# Linters & Formatters
hk = "1.48.0"

[deps.bun-aube]
description = "Automatically install dependencies via aube & bun's lockfile."
sources = [
  "package.json",
  "bun.lock"
]
outputs = [ "node_modules/" ]
# Because aube's output lockfile has bugs,
# we use `bun install --lockfile-only` to generate a lockfile
run = "bun install --lockfile-only && aube install"
auto = true

[tasks.build]
run = "echo 'Build completed!'"

[tasks.check]
run = "hk check --all"

[tasks.fix]
run = "hk fix --all"

[tasks.test]
run = "echo 'Tests passed!'"

[tasks.prerelease]
run = { tasks = [
  "check",
  "test"
] }

[tasks.release]
depends = "prerelease"
run = "bumpp"
raw = true
depends_post = "postrelease"

[tasks.changelog]
run = "changelogithub"

[tasks.postrelease]
run = "bun run ./release.sh"

[tasks.publish]
run = "echo 'Published!'"

[tasks."publish:commit"]
run = "echo 'Commit published!'"
