name: autofix.ci

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  autofix:
    uses: lumirelle/workflows/.github/workflows/ci-autofix.yml@main
    permissions:
      contents: read
