name: CI Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  coverage:
    uses: lumirelle/workflows/.github/workflows/ci-coverage.yml@v10
    permissions:
      id-token: write
