name: Release

on:
  push:
    tags: ['v*']

permissions: {}

jobs:
  release:
    uses: lumirelle/workflows/.github/workflows/release.yml@v9
    permissions:
      contents: write
      id-token: write
