name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    uses: lumirelle/workflows/.github/workflows/release.yml@v2
    with:
      publish: true
    permissions:
      contents: write
      id-token: write
