name: autofix.ci

on:
  workflow_call:
    inputs:
      primary-os:
        required: false
        type: string
        default: ubuntu-slim

      cache-preset:
        required: false
        type: string
        default: ''

      cache-preset-path:
        required: false
        type: string
        default: ''

      cache-preset-key:
        required: false
        type: string
        default: ''

      cache-preset-restore-keys:
        required: false
        type: string
        default: ''

      cache-path:
        required: false
        type: string
        default: ''

      cache-key:
        required: false
        type: string
        default: ''

      cache-restore-keys:
        required: false
        type: string
        default: ''

      fix:
        required: false
        type: string
        default: mise run fix

      debug:
        required: false
        type: boolean
        default: false

jobs:
  autofix:
    runs-on: ${{ inputs.primary-os }}
    permissions:
      contents: read
    steps:
      - name: Setup mise
        uses: lumirelle/workflows/setup-mise@v10
        with:
          cache-preset: ${{ inputs.cache-preset }}
          cache-preset-path: ${{ inputs.cache-preset-path }}
          cache-preset-key: ${{ inputs.cache-preset-key }}
          cache-preset-restore-keys: ${{ inputs.cache-preset-restore-keys }}
          cache-path: ${{ inputs.cache-path }}
          cache-key: ${{ inputs.cache-key }}
          cache-restore-keys: ${{ inputs.cache-restore-keys }}
          debug: ${{ inputs.debug }}

      - name: Fix
        run: ${{ inputs.fix }}

      - name: Commit
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
