name: CI Coverage

on:
  workflow_call:
    inputs:
      primary-os:
        required: false
        type: string
        default: ubuntu-slim

      runtime:
        required: false
        type: string
        default: bun

      test:
        required: false
        type: string
        default: nr test --coverage --if-present

jobs:
  coverage-bun:
    if: ${{ inputs.runtime == 'bun' }}
    runs-on: ${{ inputs.primary-os }}
    permissions:
      id-token: write
    steps:
      - name: Setup Bun
        if: ${{ inputs.runtime == 'bun' }}
        uses: lumirelle/workflows/setup-bun@v3

      - name: Test
        run: ${{ inputs.test }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  coverage-node:
    if: ${{ inputs.runtime == 'node' }}
    runs-on: ${{ inputs.primary-os }}
    permissions:
      id-token: write
    steps:
      - name: Setup Node
        if: ${{ inputs.runtime == 'node' }}
        uses: lumirelle/workflows/setup-node@v3

      - name: Test
        run: ${{ inputs.test }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
