name: CI

on:
  workflow_call:
    inputs:
      primary-os:
        required: false
        type: string
        default: ubuntu-slim

      os-matrix:
        required: false
        type: string
        default: '"ubuntu-slim", "macos-latest", "windows-latest"'

      bun-versions:
        required: false
        type: string
        default: '"latest"'

      node-versions:
        required: false
        type: string
        default: '20, 22, 24, 25'

      skip-check:
        required: false
        type: boolean
        default: false

      runtime:
        required: false
        type: string
        default: bun

      check:
        required: false
        type: string
        default: nr check --if-present

      test:
        required: false
        type: string
        default: nr test --if-present

jobs:
  check:
    if: ${{ !inputs.skip-check }}
    runs-on: ${{ inputs.primary-os }}
    steps:
      - name: Setup Bun
        if: ${{ inputs.runtime == 'bun' }}
        uses: lumirelle/workflows/setup-bun@v4

      - name: Setup Node
        if: ${{ inputs.runtime == 'node' }}
        uses: lumirelle/workflows/setup-node@v4

      - name: Check
        if: ${{ inputs.check != '' }}
        run: ${{ inputs.check }}

  test-bun:
    if: ${{ inputs.runtime == 'bun' }}
    strategy:
      matrix:
        os: ${{ fromJson(format('[{0}]', inputs.os-matrix)) }}
        bun: ${{ fromJson(format('[{0}]', inputs.bun-versions)) }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Bun ${{ matrix.bun }}
        if: ${{ inputs.runtime == 'bun' }}
        uses: lumirelle/workflows/setup-bun@v4
        with:
          bun-version: ${{ matrix.bun }}

      - name: Test
        run: ${{ inputs.test }}

  test-node:
    if: ${{ inputs.runtime == 'node' }}
    strategy:
      matrix:
        os: ${{ fromJson(format('[{0}]', inputs.os-matrix)) }}
        node: ${{ fromJson(format('[{0}]', inputs.node-versions)) }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node ${{ matrix.node }}
        if: ${{ inputs.runtime == 'node' }}
        uses: lumirelle/workflows/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Test
        run: ${{ inputs.test }}
