name: Release JSR

on:
  workflow_call:
    inputs:
      runtime:
        required: false
        type: string
        default: bun

      build:
        required: false
        type: string
        default: nr build

      publish:
        required: false
        type: boolean
        default: true

jobs:
  release-jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Setup Bun
        if: ${{ inputs.runtime == 'bun' }}
        uses: lumirelle/workflows/setup-bun@v3

      - name: Setup Node
        if: ${{ inputs.runtime == 'node' }}
        uses: lumirelle/workflows/setup-node@v3

      - name: Build
        run: ${{ inputs.build }}

      - name: Publish
        if: ${{ inputs.publish }}
        run: nlx jsr publish
