name: Release Commit

on:
  workflow_call:
    inputs:
      package-manager:
        required: false
        type: string
        default: bun

      build:
        required: false
        type: string
        default: mise run build

      publish:
        required: false
        type: boolean
        default: false

      compact:
        required: false
        type: boolean
        default: false

      packages:
        required: false
        type: string
        default: ''

      debug:
        required: false
        type: boolean
        default: false

jobs:
  release-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Mise
        uses: lumirelle/workflows/setup-mise@v6
        with:
          mise-local-config-tools: \"npm:pkg-pr-new\" = \"latest\"
          debug: ${{ inputs.debug }}

      - name: Debug
        if: ${{ inputs.debug }}
        shell: bash
        run: |
          set -e
          cat mise.local.toml
          which mise
          mise --version
          mise doctor
          which ni
          ni --version
          which pkg-pr-new
          pkg-pr-new --version

      - name: Build
        if: ${{ inputs.build != '' && inputs.publish }}
        run: ${{ inputs.build }}

      - name: Publish
        if: ${{ inputs.publish }}
        run: pkg-pr-new publish ${{ inputs.package-manager == 'bun' && '--bun' || '' }} ${{ inputs.package-manager == 'pnpm' && '--pnpm' || '' }} ${{ inputs.compact && '--compact' || '' }} ${{ inputs.packages }}
