name: Release

on:
  workflow_call:
    inputs:
      primary-os:
        required: false
        type: string
        default: ubuntu-latest

      cache-preset:
        required: false
        type: string
        default: ''

      cache-preset-path:
        required: false
        type: string
        default: ''

      cache-preset-key:
        required: false
        type: string
        default: ''

      cache-preset-restore-keys:
        required: false
        type: string
        default: ''

      cache-path:
        required: false
        type: string
        default: ''

      cache-key:
        required: false
        type: string
        default: ''

      cache-restore-keys:
        required: false
        type: string
        default: ''

      debug:
        required: false
        type: boolean
        default: false

      changelog:
        required: false
        type: string
        default: mise run changelog

      build:
        required: false
        type: string
        default: mise run build

      publish:
        required: false
        type: string
        default: mise run publish

jobs:
  release:
    runs-on: ${{ inputs.primary-os }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Setup mise
        id: setup-mise
        uses: lumirelle/workflows/setup-mise@v10
        with:
          fetch-all: true
          cache-preset: ${{ inputs.cache-preset }}
          cache-preset-path: ${{ inputs.cache-preset-path }}
          cache-preset-key: ${{ inputs.cache-preset-key }}
          cache-preset-restore-keys: ${{ inputs.cache-preset-restore-keys }}
          cache-path: ${{ inputs.cache-path }}
          cache-key: ${{ inputs.cache-key }}
          cache-restore-keys: ${{ inputs.cache-restore-keys }}
          debug: ${{ inputs.debug }}

      - name: Generate changelog
        if: ${{ inputs.changelog != '' }}
        run: ${{ inputs.changelog }}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: ${{ inputs.build }}

      - name: Publish
        run: ${{ inputs.publish }}
