name: Release

on:
  workflow_call:
    inputs:
      debug:
        required: false
        type: boolean
        default: false

      changelog:
        required: false
        type: boolean
        default: true

      build:
        required: false
        type: string
        default: mise run build

      publish:
        required: false
        type: boolean
        default: false

      dry-run:
        required: false
        type: boolean
        default: false

      tag:
        required: false
        type: string
        default: latest

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Setup Mise
        id: setup-mise
        uses: lumirelle/workflows/setup-mise@v7
        with:
          mise-local-config-tools: |
            aube = \"latest\"
            \"npm:changelogithub\" = \"latest\"
          fetch-all: true
          debug: ${{ inputs.debug }}

      - name: Generate GitHub Changelog
        if: ${{ inputs.changelog }}
        run: changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: ${{ inputs.build }}

      - name: Publish To NPM
        if: ${{ inputs.publish }}
        run: |
          set -euo pipefail
          shopt -s nullglob

          echo "Publishing package with aube."
          aube publish --access public ${{ inputs.dry-run == 'true' && '--dry-run' || '' }} ${{ inputs.tag && format('--tag {0}', inputs.tag) || '' }}
