name: Release

on:
  workflow_call:
    inputs:
      debug:
        required: false
        type: boolean
        default: false

      changelog:
        required: false
        type: string
        default: mise run changelog

      build:
        required: false
        type: string
        default: mise run build

      publish:
        required: false
        type: string
        default: mise run publish

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Setup Mise
        id: setup-mise
        uses: lumirelle/workflows/setup-mise@v8
        with:
          mise-local-config-tools: \"npm:changelogithub\" = \"latest\"
          fetch-all: true
          debug: ${{ inputs.debug }}

      - name: Generate GitHub Changelog
        if: ${{ inputs.changelog != '' }}
        run: ${{ inputs.changelog }}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: ${{ inputs.build }}

      - name: Publish
        run: ${{ inputs.publish }}
