name: Release Commit

on:
  workflow_call:
    inputs:
      primary-os:
        required: false
        type: string
        default: ubuntu-latest

      cache-preset:
        required: false
        type: string
        default: ''

      debug:
        required: false
        type: boolean
        default: false

      build:
        required: false
        type: string
        default: mise run build

      publish:
        required: false
        type: string
        default: mise run publish-commit

jobs:
  release-commit:
    runs-on: ${{ inputs.primary-os }}
    steps:
      - name: Setup mise
        id: setup-mise
        uses: lumirelle/workflows/setup-mise@v10
        with:
          cache-preset: ${{ inputs.cache-preset }}
          debug: ${{ inputs.debug }}

      - name: Build
        run: ${{ inputs.build }}

      - name: Publish
        run: ${{ inputs.publish }}
