name: Release Commit

on:
  workflow_call:
    inputs:
      build:
        required: false
        type: string
        default: mise run build

      publish:
        required: false
        type: boolean
        default: false

      compact:
        required: false
        type: boolean
        default: false

      packages:
        required: false
        type: string
        default: ''

      debug:
        required: false
        type: boolean
        default: false

jobs:
  release-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Mise
        id: setup-mise
        uses: lumirelle/workflows/setup-mise@v6
        with:
          mise-local-config-tools: \"npm:pkg-pr-new\" = \"latest\"
          debug: ${{ inputs.debug }}

      - name: Debug
        if: ${{ inputs.debug }}
        env:
          PACKAGE_MANAGER_NAME: ${{ steps.setup-mise.outputs.PACKAGE_MANAGER_NAME }}
        shell: bash
        run: |
          set -e
          echo "========== Mise local config: =========="
          cat mise.local.toml

          echo "========== Mise info: =========="
          which mise
          mise --version
          mise doctor

          echo "========== Package manager info: =========="
          which ${{ env.PACKAGE_MANAGER_NAME }}
          ${{ env.PACKAGE_MANAGER_NAME }} --version

          echo "========== pkg-pr-new info: =========="
          which pkg-pr-new
          pkg-pr-new --version

      - name: Build
        if: ${{ inputs.build != '' && inputs.publish }}
        run: ${{ inputs.build }}

      - name: Publish
        if: ${{ inputs.publish }}
        env:
          PACKAGE_MANAGER_NAME: ${{ steps.setup-mise.outputs.PACKAGE_MANAGER_NAME }}
        run: pkg-pr-new publish ${{ env.PACKAGE_MANAGER_NAME && format('--{0}', env.PACKAGE_MANAGER_NAME) || '' }} ${{ inputs.compact && '--compact' || '' }} ${{ inputs.packages }}
