name: Release Dogfooding

on:
  push:
    tags: ['v*']

permissions: {}

jobs:
  release:
    uses: lumirelle/workflows/.github/workflows/release.yml@main
    permissions:
      contents: write
      id-token: write
    with:
      publish: false
      packages: ./.github/* ./*
