name: Release JSR

on:
  workflow_call:
    inputs:
      build:
        required: false
        type: string
        default: mise run build

      publish:
        required: false
        type: boolean
        default: false

      debug:
        required: false
        type: boolean
        default: false

jobs:
  release-jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Setup Mise
        uses: lumirelle/workflows/setup-mise@v6
        with:
          mise-local-config-tools: \"npm:jsr\" = \"latest\"
          debug: ${{ inputs.debug }}

      - name: Debug
        if: ${{ inputs.debug }}
        shell: bash
        run: |
          set -e
          cat mise.local.toml
          which mise
          mise --version
          mise doctor
          which ni
          ni --version
          which jsr
          jsr --version

      - name: Build
        if: ${{ inputs.build != '' && inputs.publish }}
        run: ${{ inputs.build }}

      - name: Publish
        if: ${{ inputs.publish }}
        run: jsr publish
